name: Auto Release

on:
  workflow_call:
    
jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get commit sha
        shell: bash
        run: echo "COMMIT_SHA=$(echo ${GITHUB_SHA})" >> $GITHUB_ENV
      - uses: fabasoad/data-format-converter-action@main
        id: xml2json
        with:
          input: 'Config/module.xml'
          from: 'xml'
          to: 'json'    
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          commit: $COMMIT_SHA
          tag: ${{ fromJSON(steps.xml2json.outputs.output).module.version }}
          skipIfReleaseExists: true
