name: Auto Release

on:
  workflow_call:
    
jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fabasoad/data-format-converter-action@v0.2.4
        id: xml2json
        with:
          input: 'Config/module.xml'
          from: 'xml'
          to: 'json'
      - name: Get commit sha
        shell: bash
        run: echo "commit_sha=$(echo ${GITHUB_SHA})" >> "$GITHUB_OUTPUT"
        id: commit_sha
      - name: Display commit sha
        shell: bash
        run: echo ${{steps.commit_sha.outputs.commit_sha}}
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ fromJSON(steps.xml2json.outputs.output).module.version }}
          tag_exists_error: false
          commit_sha: ${{steps.commit_sha.outputs.commit_sha}}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ fromJSON(steps.xml2json.outputs.output).module.version }}
          skipIfReleaseExists: true
